import type { Metadata } from "next";
import "./globals.css";
import Provider from "./Provider";
import {AppSidebar} from "@/components/Sidebar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Provider>
          <div className="flex">
          <AppSidebar />
          <div className="h-full w-full flex items-center justify-center">
          {children}
          </div>
          </div>
        </Provider>
      </body>
    </html>
  );
}
